apiVersion: v1
kind: Service
metadata:
  name: node-port-test
  namespace: service
spec:
  selector:
    app: service-test-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort