apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  namespace: volume-mount-claim
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  local: # 로컬을 영구 볼륨으로 사용
    path: /volumes/pv01 # 로컬의 해당 경로를 볼륨으로 지정
  nodeAffinity:
    required:
      nodeSelectorTerms: # 볼륨을 사용하기 위한 노드를 식별하기 위해 사용하는 셀렉터
        - matchExpressions: # 레이블 일치 검사
            - key: dolong2 # 해당 키 레이블
              operator: In # 안에
              values:
                - volume-mount-claim # 해당 값이 존재하는 노드에서 사용가능