apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc # 볼륨 클레임 이름
  namespace: volume-mount-claim
spec:
  accessModes: # 접근 유형(필수 설정)
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Mi # 요청하는 스토리지 용량
  storageClassName: "" # 스토리지 유형(여기선 지정하지 않음)