apiVersion: v1
kind: Service
metadata:
  name: todo-web
  namespace: stateful-set
  labels:
    kiamol: ch08
spec:
  ports:
    - port: 8081
      targetPort: 80
  selector:
    app: todo-web
  type: LoadBalancer