apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  namespace: volume-mount-claim
spec:
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
        - name: sleep
          image: kiamol/ch03-sleep
          volumeMounts:
            - name: data # 볼륨 이름이 data인 볼륨을 마운트
              mountPath: /data # 볼륨을 마운트할 경로 지정
      volumes:
        - name: data # 볼륨의 이름 정의
          emptyDir: {} # 볼륨 유형 정의 EmptyDir
# 볼륨에 파일 생성
# kubectl exec -n volume-mount-claim deploy/sleep -- sh -c 'echo ch05 > /data/file.txt; ls /data/*.txt'
# 파드의 컨테이너 아이디 확인
# kubectl get pod -n volume-mount-claim -l app=sleep -o jsonpath='{.items[0].status.containerStatuses[0].containerID}'
# 컨테이너의 프로세스 종료
# kubectl exec -n volume-mount-claim -it deploy/sleep -- killall5
# 마운트된 디렉토리에 데이터가 유지되는지 확인
# kubectl exec -n volume-mount-claim deploy/sleep -- sh -c 'ls /data'