apiVersion: v1
kind: Service
metadata:
  name: pi-proxy
  namespace: scaling
  labels:
    kiamol: ch06
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: pi-proxy
  type: LoadBalancer