apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: example-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: mysql-container
        image: mysql:latest
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: mysql-env-config
      - name: redis-container
        image: redis:latest
        ports:
        - containerPort: 6379
      - name: spring-container
        image: dolong2/simple-spring-crud:0.0.1
        envFrom:
        - configMapRef:
            name: spring-env-config
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: example-backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: example-backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: example-backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort