apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
  namespace: pod-network-routing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
      - name: busybox-container
        image: busybox:latest
        command: ["sh", "-c", "sleep 3600"]
