apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2
  namespace: pod-network-routing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test2
  template:
    metadata:
      labels:
        app: test2
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80