apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-proxy-pvc
  namespace: volume-mount-claim-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi