apiVersion: v1
kind: Service
metadata:
  name: numbers-web
  namespace: multi-container
  labels:
    kiamol: ch07
spec:
  ports:
    - port: 8090
      targetPort: 80
  selector:
    app: numbers-web
  type: LoadBalancer