apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: numbers-api
  namespace: scaling-test
  labels:
    kiamol: ch06-lab
spec:
  selector:
    matchLabels:
      app: numbers-api
  template:
    metadata:
      labels:
        app: numbers-api
    spec:
      containers:
        - image: kiamol/ch03-numbers-api
          name: api
      nodeSelector:
        rng: hw