apiVersion: v1
kind: Secret
metadata:
  name: todo-web-secret
  namespace: volume-mount-claim
type: Opaque
stringData:
  secrets.json: |-
    {
      "ConnectionStrings": {kube
        "ToDoDb": "Server=todo-db;Database=todo;User Id=postgres;Password=kiamol-2*2*;"
      }
    }