apiVersion: v1
kind: Service
metadata:
  name: numbers-api
  namespace: service-test
spec:
  ports:
    - port: 80
  type: ClusterIP # selector 필드가 없으므로 헤드리스 서비스가 됨
--- # 한파일에 여러 리소스 정의
apiVersion: v1
kind: Endpoints
metadata:
  name: numbers-api
  namespace: service-test
subsets:
  - addresses: # 정적 IP 주소 목록
      - ip: 192.168.123.234
    ports: # 각 IP 주소에서 주시할 포트
      - port: 80