apiVersion: v1
kind: Service
metadata:
  name: pi-version
  namespace: multi-container-test
  labels:
    kiamol: ch07-lab
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: pi-web
  type: LoadBalancer