apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-env-deployment
  namespace: config-map
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmap-env-deployment
  template:
    metadata:
      labels:
        app: configmap-env-deployment
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
        # 이 아래 부분을 통해서 config map을 컨테이너의 환경변수로 사용할 수 있음
        envFrom:
        - configMapRef:
            name: test-config-map