apiVersion: v1
kind: Service
metadata:
  name: timecheck
  namespace: multi-container
  labels:
    kiamol: ch07
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: healthz
    - port: 8081
      targetPort: 8081
      name: metrics
  selector:
    app: timecheck
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timecheck
  namespace: multi-container
  labels:
    kiamol: ch07
spec:
  selector:
    matchLabels:
      app: timecheck
  template:
    metadata:
      labels:
        app: timecheck
        version: v4
    spec:
      initContainers:
        - name: init-config
          image: kiamol/ch03-sleep
          command: ['sh', '-c', "cat /config-in/appsettings.json | jq --arg APP_ENV \"$APP_ENVIRONMENT\" '.Application.Environment=$APP_ENV' > /config-out/appsettings.json"]
          env:
            - name: APP_ENVIRONMENT # 모든 컨테이너는 각자의 환경변수를 가질 수 있다.
              value: TEST # 해당 환경변수는 파드 단위에서 공유되지 않는다.
          volumeMounts:
            - name: config-map # 컨피그맵 마운트
              mountPath: /config-in
            - name: config-dir # 초기화 컨테이너에서 구성된 설정을 기록할 empty 디렉토리
              mountPath: /config-out
      containers:
        - name: timecheck
          image: kiamol/ch07-timecheck
          volumeMounts:
            - name: config-dir
              mountPath: /config
              readOnly: true
            - name: logs-dir # 마운트된 볼륨에 로그 파일 생성
              mountPath: /logs
        - name: logger
          image: kiamol/ch03-sleep
          command:
            - sh
            - -c
            - tail -f /logs-ro/timecheck.log # tail 명령으로 마운트된 볼륨의 로그 파일의 내용을 출력하므로, logger 컨테이너의 로그 조회시 기록된 타임스탬프 확인 가능
          volumeMounts:
            - name: logs-dir
              mountPath: /logs-ro
              readOnly: true
        - name: healthz
          image: kiamol/ch03-sleep
          command: [ 'sh', '-c', "while true; do echo -e 'HTTP/1.1 200 OK\nContent-Type: application/json\nContent-Length: 17\n\n{\"status\": \"OK\"}' | nc -l -p 8080; done" ]
          ports:
            - containerPort: 8080
              name: http
        - name: metrics
          image: kiamol/ch03-sleep
          command: [ 'sh', '-c', "while true; do echo -e 'HTTP/1.1 200 OK\nContent-Type: text/plain\nContent-Length: 104\n\n# HELP timechecks_total The total number timechecks.\n# TYPE timechecks_total counter\ntimechecks_total 6' | nc -l -p 8081; done" ]
          ports:
            - containerPort: 8081
              name: http
      volumes:
        - name: config-map
          configMap:
            name: timecheck-config
        - name: config-dir
          emptyDir: {}
        - name: logs-dir
          emptyDir: {}