apiVersion: apps/v1
kind: Deployment
metadata:
  name: timecheck
  namespace: multi-container
  labels:
    kiamol: ch07
spec:
  selector:
    matchLabels:
      app: timecheck
  template:
    metadata:
      labels:
        app: timecheck
    spec:
      containers:
        - name: timecheck
          image: kiamol/ch07-timecheck
# 기록된 타임스탬프 확인
# kubectl exec -n multi-container deploy/timecheck -- cat /logs/timecheck.log
# 애플리케이션 설정 확인
# kubectl exec -n multi-container deploy/timecheck -- cat /config/appsettings.json