apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  labels:
    kiamol: ch07
  namespace: multi-container
spec:
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers: # 컨테이너 필드의 형태는 배열
        - name: sleep
          image: kiamol/ch03-sleep
        - name: server
          image: kiamol/ch03-sleep
          command: ['sh', '-c', "while true; do echo -e 'HTTP/1.1 200 OK\nContent-Type: text/plain\nContent-Length: 7\n\nkiamol' | nc -l -p 8080; done"]
          ports:
            - containerPort: 8080 # 애플리케이션이 사용하는 포트를 기록
              name: http
# 아래의 명령을 통해 통신확인 가능
# kubectl exec deploy/sleep -c sleep -n multi-container -- wget -q -O - localhost:8080
# kubectl logs -l app=sleep -c server -n multi-container