apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  labels:
    kiamol: ch07
  namespace: multi-container
spec:
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      initContainers:
        - name: init-html
          image: kiamol/ch03-sleep
          command:
            - sh
            - -c
            - echo '<!DOCTYPE html><html><body><h1>KIAMOL Ch07</h1></body></html>' > /data/index.html
          volumeMounts:
            - mountPath: /data
              name: data
      containers: # 컨테이너 필드의 형태는 배열
        - name: sleep
          image: kiamol/ch03-sleep
        - name: server
          image: kiamol/ch03-sleep
          command: ['sh', '-c', 'while true; do echo -e "HTTP/1.1 200 OK\nContent-Type: text/html\nContent-Length: 62\n\n$(cat /data-ro/index.html)" | nc -l -p 8080; done']
          ports:
            - containerPort: 8080 # 애플리케이션이 사용하는 포트를 기록
              name: http
          volumeMounts:
            - name: data
              mountPath: /data-ro
              readOnly: true
      volumes:
        - name: data # 같은 볼륨은 여러 컨테이너에 마운트할 수 있다
          emptyDir: { }