apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  namespace: env-or-configmap
spec:
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
        - name: sleep
          image: kiamol/ch03-sleep
          env:
          - name: KIAMOL_SECRET # 컨테이너에 전달될 환경변수 이름
            valueFrom: # 환경 변수의 값을 외부에서 가져옴
              secretKeyRef: # 비밀값에서 참조
                name: sleep-secret-literal # 비밀값 이름
                key: secret # 비밀값의 항목이름