apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-web-config-dev
  namespace: env-or-configmap
data:
  config.json: |-
    {
      "ConfigController": {
        "Enabled": true
      }
    }
  logging.json: |-
    {
      "Logging": {
        "LogLevel": {
          "ToDoList.Pages": "Debug"
        }
      }
    }