# 실제 서비스 운영시에는 노출되면 안됨
apiVersion: v1
kind: Secret # 리소스 유형은 비밀값
metadata:
  name: todo-db-secret-test # 비밀값 이름
  namespace: env-or-configmap
type: Opaque # 텍스트 데이터를 담기위한 유형
stringData: # 텍스트 데이터
  POSTGRES_PASSWORD: "kiamol-2*2*" # 저장할 데이터(키-값)